load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "reachability",
    srcs = [
        "analyzer.go",
        "coverability.go",
        "farkas.go",
        "graph.go",
        "invariants.go",
        "marking.go",
        "spectral.go",
    ],
    importpath = "github.com/pflow-xyz/go-pflow/reachability",
    visibility = ["//visibility:public"],
    deps = ["//petri"],
)

go_test(
    name = "reachability_test",
    srcs = [
        "coverability_test.go",
        "farkas_test.go",
        "invariants_string_test.go",
        "reachability_test.go",
    ],
    embed = [":reachability"],
    deps = ["//petri"],
)
