load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "petri",
    srcs = [
        "builder.go",
        "colors.go",
        "net.go",
    ],
    importpath = "github.com/pflow-xyz/go-pflow/petri",
    visibility = ["//visibility:public"],
)

go_test(
    name = "petri_test",
    srcs = [
        "builder_test.go",
        "colors_test.go",
        "net_test.go",
    ],
    embed = [":petri"],
)
