load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "statemachine",
    srcs = [
        "builder.go",
        "machine.go",
        "metasubnet.go",
        "model.go",
        "types.go",
    ],
    importpath = "github.com/pflow-xyz/go-pflow/statemachine",
    visibility = ["//visibility:public"],
    deps = [
        "//engine",
        "//metamodel",
        "//petri",
        "//tokenmodel/petri",
        "//tokenmodel/subnet",
    ],
)

go_test(
    name = "statemachine_test",
    srcs = [
        "metasubnet_test.go",
        "model_test.go",
        "statemachine_test.go",
    ],
    embed = [":statemachine"],
    deps = [
        "//metamodel",
        "//metamodel/metapetri",
        "//reachability",
        "//tokenmodel/dataflow/transport",
        "//tokenmodel/petri",
        "//tokenmodel/subnet",
    ],
)
