load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "actor",
    srcs = [
        "actor.go",
        "builder.go",
        "bus.go",
        "metabundle.go",
        "subnet.go",
        "types.go",
    ],
    importpath = "github.com/pflow-xyz/go-pflow/actor",
    visibility = ["//visibility:public"],
    deps = [
        "//engine",
        "//metamodel",
        "//petri",
        "//solver",
        "//tokenmodel/petri",
        "//tokenmodel/subnet",
        "//workflow",
    ],
)

go_test(
    name = "actor_test",
    srcs = [
        "actor_test.go",
        "colors_test.go",
        "metabundle_guard_test.go",
        "metabundle_test.go",
        "pubsub_test.go",
        "subnet_test.go",
    ],
    embed = [":actor"],
    deps = [
        "//metamodel",
        "//metamodel/metapetri",
        "//petri",
        "//tokenmodel/subnet",
        "//verify",
    ],
)
