// Command shape-goldens writes the editor-shape parse goldens under
// parser/testdata/editor-shape/, one per input document: the parsed colored
// net, its color expansion and its unfolded metamodel, as go-pflow reads
// them. Copies of these files are the parity fixtures for every other
// reader of the pflow.xyz editor shape (pflow-jl, pflow-xyz's browser
// modules). Regenerate only when go-pflow's reading changes on purpose,
// and say why in the commit.
//
//	go run ./cmd/shape-goldens <name>=<path.jsonld> ...
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/pflow-xyz/go-pflow/parser"
)

func main() {
	outDir := filepath.Join("parser", "testdata", "editor-shape")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fail(err)
	}
	for _, arg := range os.Args[1:] {
		name, path, ok := strings.Cut(arg, "=")
		if !ok {
			fail(fmt.Errorf("want name=path, got %q", arg))
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			fail(err)
		}
		g, err := parser.BuildEditorShapeGolden(
			fmt.Sprintf("editor-shape parse golden %q generated by go-pflow cmd/shape-goldens from %s; every reader of the pflow.xyz editor shape must reproduce parsed (and expanded, where it unfolds colors)", name, filepath.Base(path)),
			raw)
		if err != nil {
			fail(fmt.Errorf("%s: %w", name, err))
		}
		data, err := json.MarshalIndent(g, "", " ")
		if err != nil {
			fail(err)
		}
		out := filepath.Join(outDir, name+".json")
		if err := os.WriteFile(out, append(data, '\n'), 0o644); err != nil {
			fail(err)
		}
		fmt.Printf("%s (%d bytes)\n", out, len(data))
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "shape-goldens:", err)
	os.Exit(1)
}
