load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "incident_simulator_lib",
    srcs = ["main.go"],
    importpath = "github.com/pflow-xyz/go-pflow/examples/incident_simulator",
    visibility = ["//visibility:private"],
    deps = [
        "//eventlog",
        "//mining",
        "//monitoring",
        "//visualization",
    ],
)

go_binary(
    name = "incident_simulator",
    embed = [":incident_simulator_lib"],
    visibility = ["//visibility:public"],
)
