load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "visualization_demo_lib",
    srcs = ["main.go"],
    importpath = "github.com/pflow-xyz/go-pflow/examples/visualization_demo",
    visibility = ["//visibility:private"],
    deps = [
        "//petri",
        "//statemachine",
        "//visualization",
        "//workflow",
    ],
)

go_binary(
    name = "visualization_demo",
    embed = [":visualization_demo_lib"],
    visibility = ["//visibility:public"],
)
