load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "ssa-goldens_lib",
    srcs = ["main.go"],
    importpath = "github.com/pflow-xyz/go-pflow/cmd/ssa-goldens",
    visibility = ["//visibility:private"],
    deps = [
        "//metamodel",
        "//stochastic",
    ],
)

go_binary(
    name = "ssa-goldens",
    embed = [":ssa-goldens_lib"],
    visibility = ["//visibility:public"],
)
