load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "stateutil",
    srcs = ["stateutil.go"],
    importpath = "github.com/pflow-xyz/go-pflow/stateutil",
    visibility = ["//visibility:public"],
)

go_test(
    name = "stateutil_test",
    srcs = ["stateutil_test.go"],
    embed = [":stateutil"],
)
