load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "pflow_lib",
    srcs = [
        "analyze.go",
        "args.go",
        "compare.go",
        "create.go",
        "events.go",
        "expand.go",
        "main.go",
        "plot.go",
        "simulate.go",
        "summary.go",
        "sweep.go",
        "validate.go",
        "verify.go",
        "visualize.go",
    ],
    importpath = "github.com/pflow-xyz/go-pflow/cmd/pflow",
    visibility = ["//visibility:private"],
    deps = [
        "//parser",
        "//petri",
        "//plotter",
        "//results",
        "//solver",
        "//templates",
        "//validation",
        "//verify",
        "//visualization",
    ],
)

go_binary(
    name = "pflow",
    embed = [":pflow_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "pflow_test",
    srcs = ["args_test.go"],
    embed = [":pflow_lib"],
)
