load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "main_lib",
    srcs = ["main.go"],
    importpath = "github.com/pflow-xyz/go-pflow/examples/neural/cmd/main",
    visibility = ["//visibility:private"],
    deps = [
        "//learn",
        "//petri",
        "//plotter",
        "//solver",
    ],
)

go_binary(
    name = "main",
    embed = [":main_lib"],
    visibility = ["//visibility:public"],
)
